name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust as needed

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  
